In [1]:
import numpy as np

In [2]:
a = list (range (1_000_000))

In [3]:
%%timeit 

[e * e for e in a]

179 ms ± 13.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
a = np.arange (1_000_000)

In [7]:
%%timeit 

a * a

2.95 ms ± 616 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
rows, cols = 1_000, 1_000

a = [list(range(i, i + cols)) for i in range (rows)]
b = [[0 for j in range(cols)] for i in range (rows)]

In [9]:
%%timeit

for i in range(rows):
    for j in range(cols):
        b[i][j] = 2 * a[i][j]

306 ms ± 59.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
a = np.asarray(a)

In [11]:
%%timeit

b = 2 * a 

3.47 ms ± 283 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
a = np.array([1,2,3,4,5])
a, type(a)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [13]:
a.shape

(5,)

In [20]:
tuple_1 = ('Hello'); print (tuple_1)

Hello


In [21]:
tuple_1 = ('Hello', ); print (tuple_1)

('Hello',)


In [22]:
a.dtype

dtype('int32')

In [24]:
a = np.array([1.,2.,3.,4.,5.])
a, type(a), a.dtype

(array([1., 2., 3., 4., 5.]), numpy.ndarray, dtype('float64'))

In [26]:
a = np.array([1,2,3,4,5], dtype=np.float32)
a, type(a), a.dtype

(array([1., 2., 3., 4., 5.], dtype=float32), numpy.ndarray, dtype('float32'))

In [27]:
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [29]:
a, a.astype(np.complex), a.astype(np.int64)

C:\Users\User\AppData\Local\Temp\ipykernel_2352\3012408652.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a, a.astype(np.complex), a.astype(np.int64)


(array([1., 2., 3., 4., 5.], dtype=float32),
 array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j]),
 array([1, 2, 3, 4, 5], dtype=int64))

In [30]:
a = np.arange (15)
a[10]=100
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,  11,  12,
        13,  14])

In [32]:
a[0], a[5], a[len(a)-1], a[-1]

(0, 5, 14, 14)

In [33]:
array[start=0:stop=len(array)-1:step=1]

SyntaxError: invalid syntax (3079450452.py, line 1)

In [35]:
a = np.arange (15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
variants = [ a[0:5:1], a[0:5], a[:5]]
variants

[array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4])]

In [38]:
slice(stop), slice(start, stop[, step])

SyntaxError: invalid syntax (2877692536.py, line 1)

In [40]:
variants = [ a[slice(0,5,1)], a[slice(0,5)], a[slice(5)]]
variants

[array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4])]

In [41]:
variants = [ a[0:len(a):2], a[0::2], a[::2]]
variants

[array([ 0,  2,  4,  6,  8, 10, 12, 14]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14])]

In [42]:
variants = [ a[1:len(a):2], a[1::2]]
variants

[array([ 1,  3,  5,  7,  9, 11, 13]), array([ 1,  3,  5,  7,  9, 11, 13])]

In [43]:
variants = [ a[3:12:3], a[3:-3:3]]
variants

[array([3, 6, 9]), array([3, 6, 9])]

In [44]:
variants = [ a[3:13:3][::-1], a[12:2:-3], a[-3:2:-3]]
variants

[array([12,  9,  6,  3]), array([12,  9,  6,  3]), array([12,  9,  6,  3])]

In [45]:
a = np.array([1,2,3,4,5])
mask = np.array([False, True, True, False, True])
mask, a, a[mask]

(array([False,  True,  True, False,  True]),
 array([1, 2, 3, 4, 5]),
 array([2, 3, 5]))

In [46]:
np.random.seed(1024)
a = np.random.randint(-2,7,34)
a

array([-1, -1,  3, -1, -2, -2,  1,  0, -2,  5,  6,  5, -1,  0,  1,  3, -2,
        3,  3,  1, -2,  4,  4,  3,  4,  2,  2, -1, -2, -1,  6,  5, -2, -1])

In [47]:
a[a<0]

array([-1, -1, -1, -2, -2, -2, -1, -2, -2, -1, -2, -1, -2, -1])

In [48]:
variants = [ a[a%3==0], a[np.logical_not(a%3)], a[~((a%3).astype(bool))]]
variants

[array([3, 0, 6, 0, 3, 3, 3, 3, 6]),
 array([3, 0, 6, 0, 3, 3, 3, 3, 6]),
 array([3, 0, 6, 0, 3, 3, 3, 3, 6])]

In [49]:
np.random.seed(1234)
a = np.random.randint(0,9,23)
a

array([3, 6, 5, 4, 8, 1, 7, 6, 8, 0, 5, 0, 6, 2, 0, 5, 2, 6, 3, 7, 0, 0,
       3])

In [50]:
mask_3 = a % 3 == 0
mask_5 = a % 5 == 0

variants = [ a [np.logical_or(mask_3, mask_5)], a[mask_3|mask_5] ]

mask_3, mask_5, a, variants

(array([ True,  True, False, False, False, False, False,  True, False,
         True, False,  True,  True, False,  True, False, False,  True,
         True, False,  True,  True,  True]),
 array([False, False,  True, False, False, False, False, False, False,
         True,  True,  True, False, False,  True,  True, False, False,
        False, False,  True,  True, False]),
 array([3, 6, 5, 4, 8, 1, 7, 6, 8, 0, 5, 0, 6, 2, 0, 5, 2, 6, 3, 7, 0, 0,
        3]),
 [array([3, 6, 5, 6, 0, 5, 0, 6, 0, 5, 6, 3, 0, 0, 3]),
  array([3, 6, 5, 6, 0, 5, 0, 6, 0, 5, 6, 3, 0, 0, 3])])

In [51]:
mask = np.array([True, True, False, True, False])
mask, np.where(mask)

(array([ True,  True, False,  True, False]), (array([0, 1, 3], dtype=int64),))

In [52]:
np.where(a>0)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 12, 13, 15, 16, 17, 18, 19,
        22], dtype=int64),)

In [53]:
a[np.where(a>0)]

array([3, 6, 5, 4, 8, 1, 7, 6, 8, 5, 6, 2, 5, 2, 6, 3, 7, 3])

In [54]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,0]], dtype=np.float32)
a, a.shape, a.dtype

(array([[1., 2., 3., 4., 5.],
        [6., 7., 8., 9., 0.]], dtype=float32),
 (2, 5),
 dtype('float32'))

In [55]:
a.ndim

2

In [56]:
len(a.shape)

2

In [57]:
a = np.array (
    [
        [
            [0, 1, 2, 3],
            [4, 5, 6, 7],
            [8, 9, 10, 11]
        ],
        [
            [12, 13, 14, 15],
            [16, 17, 18, 19],
            [20, 21, 22, 23]
        ],
        [
            [24, 25, 26, 27],
            [28, 29, 30, 31],
            [32, 33, 34, 35]
        ],
        [
            [36, 37, 38, 39],
            [40, 41, 42, 43],
            [44, 45, 46, 47]
        ]
    ])
a, a.shape, a.ndim, a.dtype

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],
 
        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],
 
        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]),
 (4, 3, 4),
 3,
 dtype('int32'))

In [58]:
a = np. arange(30). reshape(5, -1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [59]:
a[0][0], a[0][2], a[1][1], a[-1][-2]

(0, 2, 7, 28)

In [60]:
a[0,0], a[0,2], a[1,1], a[-1,-2]

(0, 2, 7, 28)

In [61]:
variants = [ a[2], a[2,:]]
variants

[array([12, 13, 14, 15, 16, 17]), array([12, 13, 14, 15, 16, 17])]

In [62]:
a[:,3]

array([ 3,  9, 15, 21, 27])

In [63]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [64]:
a[0,1::2]

array([1, 3, 5])

In [65]:
a,a[1::2,2::3][::-1]

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[20, 23],
        [ 8, 11]]))

In [66]:
a = np. arange(30). reshape(5, -1)
a, a[[2,4,3]]

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[12, 13, 14, 15, 16, 17],
        [24, 25, 26, 27, 28, 29],
        [18, 19, 20, 21, 22, 23]]))

In [67]:
a, a[:,[0,-1]]

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[ 0,  5],
        [ 6, 11],
        [12, 17],
        [18, 23],
        [24, 29]]))

In [68]:
a[[2,4,3]][:,[0,-1]]

array([[12, 17],
       [24, 29],
       [18, 23]])

In [69]:
a = np.arange(24).reshape(2,3,4)
a, a[...,0]

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[ 0,  4,  8],
        [12, 16, 20]]))

In [70]:
a, a[1,...]

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [71]:
a, a[...,0,:]

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]))