# Импорт библиотек

In [ ]:
pip install numpy

In [1]:
import numpy as np
import tensorflow as tf

from tensorflow import keras

In [2]:
pip freeze

absl-py==1.4.0
alabaster @ file:///home/ktietz/src/ci/alabaster_1611921544520/work
anaconda-client==1.11.0
anaconda-navigator==2.3.1
anaconda-project @ file:///C:/Windows/TEMP/abs_91fu4tfkih/croots/recipe/anaconda-project_1660339890874/work
anyio @ file:///C:/ci/anyio_1644481921011/work/dist
appdirs==1.4.4
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///C:/ci/argon2-cffi-bindings_1644551690056/work
arrow @ file:///opt/conda/conda-bld/arrow_1649166651673/work
astroid @ file:///C:/Windows/TEMP/abs_b0dtxgpicv/croots/recipe/astroid_1659023126745/work
astropy @ file:///C:/ci/astropy_1657719656942/work
astunparse==1.6.3
atomicwrites==1.4.0
attrs @ file:///opt/conda/conda-bld/attrs_1642510447205/work
Automat @ file:///tmp/build/80754af9/automat_1600298431173/work
autopep8 @ file:///opt/conda/conda-bld/autopep8_1650463822033/work
Babel @ file:///tmp/build/80754af9/babel_1620871417480/work
backcall @ file:///home/ktietz/src/ci/backcall_161

In [3]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.


Версии

In [4]:
tf.__version__

'2.11.0'

In [5]:
np.__version__

'1.21.5'

In [6]:
import sys
sys.version

'3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]'

In [ ]:
pip freeze

In [ ]:
pip freeze > requirements.txt

Docker

pip install -r requirements.txt

---

# Сохранение базовой модели

Пример модели

In [7]:
def get_model():
    inputs = keras.Input(shape=(32,))
#     layer1 = keras.layers.Dense(5)(inputs)
#     outputs = keras.layers.Dense(1)(layer1)
    outputs = keras.layers.Dense(1)(inputs)
    
    model = keras.Model(inputs, outputs)
    model.compile(optimizer="adam", loss="mean_squared_error")
    
    return model

In [24]:
model = get_model()

In [25]:
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [26]:
# Имитация набора данных: 2048 примеров
tmp_input = np.random.random((2048, 32))
tmp_target = np.random.random((2048, 1))

In [27]:
tmp_input.shape

(2048, 32)

In [28]:
tmp_input

array([[0.63861921, 0.07184638, 0.69075763, ..., 0.69650238, 0.58579723,
        0.22211401],
       [0.62685005, 0.49302758, 0.31877969, ..., 0.0156235 , 0.60788035,
        0.61767494],
       [0.73807751, 0.13266912, 0.41776186, ..., 0.70439825, 0.81391737,
        0.68549572],
       ...,
       [0.43586449, 0.34501931, 0.62202586, ..., 0.7591058 , 0.00660977,
        0.56575764],
       [0.00625309, 0.14313248, 0.08576439, ..., 0.44052558, 0.93255586,
        0.02799844],
       [0.75514743, 0.66524905, 0.02627325, ..., 0.1805354 , 0.94515254,
        0.60796969]])

In [29]:
model.fit(tmp_input, tmp_target, epochs=4)

Epoch 1/4
64/64 [==============================] - 0s 1ms/step - loss: 0.3104
Epoch 2/4
64/64 [==============================] - 0s 2ms/step - loss: 0.1764
Epoch 3/4
64/64 [==============================] - 0s 2ms/step - loss: 0.1695
Epoch 4/4
64/64 [==============================] - 0s 2ms/step - loss: 0.1621


In [30]:
?model.fit

In [16]:
model.fit(tmp_input, tmp_target, epochs=10)

Epoch 1/10
64/64 [==============================] - 0s 2ms/step - loss: 0.2454
Epoch 2/10
64/64 [==============================] - 0s 2ms/step - loss: 0.2330
Epoch 3/10
64/64 [==============================] - 0s 1ms/step - loss: 0.2207
Epoch 4/10
64/64 [==============================] - 0s 1ms/step - loss: 0.2088
Epoch 5/10
64/64 [==============================] - 0s 2ms/step - loss: 0.1969
Epoch 6/10
64/64 [==============================] - 0s 3ms/step - loss: 0.1857
Epoch 7/10
64/64 [==============================] - 0s 1ms/step - loss: 0.1749
Epoch 8/10
64/64 [==============================] - 0s 2ms/step - loss: 0.1653
Epoch 9/10
64/64 [==============================] - 0s 2ms/step - loss: 0.1563
Epoch 10/10
64/64 [==============================] - 0s 1ms/step - loss: 0.1481


In [31]:
a = get_model()

In [32]:
a.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [19]:
model = 1

In [33]:
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.fit(tmp_input, tmp_target, epochs=10)

Epoch 1/10
64/64 [==============================] - 0s 2ms/step - loss: 0.1545
Epoch 2/10
64/64 [==============================] - 0s 1ms/step - loss: 0.1468
Epoch 3/10
64/64 [==============================] - 0s 1ms/step - loss: 0.1395
Epoch 4/10
64/64 [==============================] - 0s 1ms/step - loss: 0.1328
Epoch 5/10
64/64 [==============================] - 0s 1ms/step - loss: 0.1262
Epoch 6/10
64/64 [==============================] - 0s 1ms/step - loss: 0.1204
Epoch 7/10
64/64 [==============================] - 0s 2ms/step - loss: 0.1151
Epoch 8/10
64/64 [==============================] - 0s 3ms/step - loss: 0.1104
Epoch 9/10
64/64 [==============================] - 0s 2ms/step - loss: 0.1064
Epoch 10/10
64/64 [==============================] - 0s 2ms/step - loss: 0.1028


AttributeError: 'int' object has no attribute 'type'

In [35]:
model = get_model()

In [36]:
model.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.fit(tmp_input, tmp_target, epochs=5)

Epoch 1/5
64/64 [==============================] - 0s 1ms/step - loss: 0.5436
Epoch 2/5
64/64 [==============================] - 0s 2ms/step - loss: 0.2308
Epoch 3/5
64/64 [==============================] - 0s 2ms/step - loss: 0.2200
Epoch 4/5
64/64 [==============================] - 0s 1ms/step - loss: 0.2111
Epoch 5/5
64/64 [==============================] - 0s 1ms/step - loss: 0.2017


Сохранение

In [44]:
model_path = "my_model_1"

model_path = "D:/work/project1/my_model_1"  
model_path = "C:/eugenia/project1/my_model_1"  
не рекомендуется абсолютный  путь

In [45]:
model.save(model_path)

INFO:tensorflow:Assets written to: my_model_1\assets


INFO:tensorflow:Assets written to: my_model_1\assets


Загрузка модели

In [46]:
reconstructed_model = keras.models.load_model(model_path)

In [47]:
reconstructed_model.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [48]:
model.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [49]:
model.weights

[<tf.Variable 'dense_4/kernel:0' shape=(32, 1) dtype=float32, numpy=
 array([[ 0.08514459],
        [-0.10109646],
        [ 0.01877539],
        [ 0.00563872],
        [ 0.31376886],
        [-0.22132404],
        [-0.13791648],
        [-0.01779721],
        [-0.23778038],
        [ 0.33365735],
        [-0.30234456],
        [ 0.02102913],
        [ 0.13429612],
        [ 0.08012009],
        [ 0.01181314],
        [ 0.118499  ],
        [ 0.24817105],
        [ 0.07466882],
        [ 0.19132245],
        [ 0.358819  ],
        [ 0.31965876],
        [ 0.14399889],
        [-0.10243303],
        [-0.21835056],
        [ 0.01463337],
        [-0.12632428],
        [-0.04070312],
        [-0.03949545],
        [-0.31820065],
        [-0.27572954],
        [ 0.07404938],
        [ 0.4147861 ]], dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(1,) dtype=float32, numpy=array([0.06133759], dtype=float32)>]

In [50]:
reconstructed_model.weights

[<tf.Variable 'dense_4/kernel:0' shape=(32, 1) dtype=float32, numpy=
 array([[ 0.08514459],
        [-0.10109646],
        [ 0.01877539],
        [ 0.00563872],
        [ 0.31376886],
        [-0.22132404],
        [-0.13791648],
        [-0.01779721],
        [-0.23778038],
        [ 0.33365735],
        [-0.30234456],
        [ 0.02102913],
        [ 0.13429612],
        [ 0.08012009],
        [ 0.01181314],
        [ 0.118499  ],
        [ 0.24817105],
        [ 0.07466882],
        [ 0.19132245],
        [ 0.358819  ],
        [ 0.31965876],
        [ 0.14399889],
        [-0.10243303],
        [-0.21835056],
        [ 0.01463337],
        [-0.12632428],
        [-0.04070312],
        [-0.03949545],
        [-0.31820065],
        [-0.27572954],
        [ 0.07404938],
        [ 0.4147861 ]], dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(1,) dtype=float32, numpy=array([0.06133759], dtype=float32)>]

Сравнение моделей

In [51]:
?np.testing.assert_allclose

In [52]:
help(np.testing.assert_allclose)

Help on function assert_allclose in module numpy.testing._private.utils:

assert_allclose(actual, desired, rtol=1e-07, atol=0, equal_nan=True, err_msg='', verbose=True)
    Raises an AssertionError if two objects are not equal up to desired
    tolerance.
    
    The test is equivalent to ``allclose(actual, desired, rtol, atol)`` (note
    that ``allclose`` has different default values). It compares the difference
    between `actual` and `desired` to ``atol + rtol * abs(desired)``.
    
    .. versionadded:: 1.5.0
    
    Parameters
    ----------
    actual : array_like
        Array obtained.
    desired : array_like
        Array desired.
    rtol : float, optional
        Relative tolerance.
    atol : float, optional
        Absolute tolerance.
    equal_nan : bool, optional.
        If True, NaNs will compare equal.
    err_msg : str, optional
        The error message to be printed in case of failure.
    verbose : bool, optional
        If True, the conflicting values are ap

In [53]:
reconstructed_model.get_weights()[0]

array([[ 0.08514459],
       [-0.10109646],
       [ 0.01877539],
       [ 0.00563872],
       [ 0.31376886],
       [-0.22132404],
       [-0.13791648],
       [-0.01779721],
       [-0.23778038],
       [ 0.33365735],
       [-0.30234456],
       [ 0.02102913],
       [ 0.13429612],
       [ 0.08012009],
       [ 0.01181314],
       [ 0.118499  ],
       [ 0.24817105],
       [ 0.07466882],
       [ 0.19132245],
       [ 0.358819  ],
       [ 0.31965876],
       [ 0.14399889],
       [-0.10243303],
       [-0.21835056],
       [ 0.01463337],
       [-0.12632428],
       [-0.04070312],
       [-0.03949545],
       [-0.31820065],
       [-0.27572954],
       [ 0.07404938],
       [ 0.4147861 ]], dtype=float32)

In [54]:
np.testing.assert_allclose(model.get_weights()[0], 
                           reconstructed_model.get_weights()[0], 
                           rtol=0.0000001)

In [55]:
np.testing.assert_allclose([1, 2, 3], 
                           [22, 22, 22])

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 3 / 3 (100%)
Max absolute difference: 21
Max relative difference: 0.95454545
 x: array([1, 2, 3])
 y: array([22, 22, 22])

In [56]:
model == reconstructed_model

False

In [57]:
model

In [58]:
reconstructed_model

Продолжение обучения

In [59]:
reconstructed_model.fit(tmp_input, tmp_target, epochs=20)

Epoch 1/20
64/64 [==============================] - 1s 3ms/step - loss: 0.1869
Epoch 2/20
64/64 [==============================] - 0s 2ms/step - loss: 0.1664
Epoch 3/20
64/64 [==============================] - 0s 2ms/step - loss: 0.1498
Epoch 4/20
64/64 [==============================] - 0s 3ms/step - loss: 0.1362
Epoch 5/20
64/64 [==============================] - 0s 3ms/step - loss: 0.1252
Epoch 6/20
64/64 [==============================] - 0s 3ms/step - loss: 0.1167
Epoch 7/20
64/64 [==============================] - 0s 3ms/step - loss: 0.1093
Epoch 8/20
64/64 [==============================] - 0s 3ms/step - loss: 0.1041
Epoch 9/20
64/64 [==============================] - 0s 4ms/step - loss: 0.0992
Epoch 10/20
64/64 [==============================] - 0s 3ms/step - loss: 0.0956
Epoch 11/20
64/64 [==============================] - 0s 3ms/step - loss: 0.0928
Epoch 12/20
64/64 [==============================] - 0s 3ms/step - loss: 0.0909
Epoch 13/20
64/64 [==============================

In [60]:
np.testing.assert_allclose(model.get_weights()[0], 
                           reconstructed_model.get_weights()[0], 
                           rtol=0.0000001)

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 32 / 32 (100%)
Max absolute difference: 0.39436132
Max relative difference: 52.43441
 x: array([[ 0.085145],
       [-0.101096],
       [ 0.018775],...
 y: array([[ 0.06372 ],
       [ 0.017928],
       [ 0.044709],...

In [61]:
model.get_weights()[0]

array([[ 0.08514459],
       [-0.10109646],
       [ 0.01877539],
       [ 0.00563872],
       [ 0.31376886],
       [-0.22132404],
       [-0.13791648],
       [-0.01779721],
       [-0.23778038],
       [ 0.33365735],
       [-0.30234456],
       [ 0.02102913],
       [ 0.13429612],
       [ 0.08012009],
       [ 0.01181314],
       [ 0.118499  ],
       [ 0.24817105],
       [ 0.07466882],
       [ 0.19132245],
       [ 0.358819  ],
       [ 0.31965876],
       [ 0.14399889],
       [-0.10243303],
       [-0.21835056],
       [ 0.01463337],
       [-0.12632428],
       [-0.04070312],
       [-0.03949545],
       [-0.31820065],
       [-0.27572954],
       [ 0.07404938],
       [ 0.4147861 ]], dtype=float32)

In [62]:
reconstructed_model.get_weights()[0]

array([[ 0.06372016],
       [ 0.01792771],
       [ 0.04470944],
       [ 0.02292729],
       [ 0.0503382 ],
       [-0.01125977],
       [ 0.02684504],
       [ 0.01445989],
       [-0.02791958],
       [ 0.02947246],
       [-0.01158235],
       [ 0.05327379],
       [ 0.01703331],
       [-0.01007107],
       [ 0.04734327],
       [ 0.04907845],
       [ 0.05834931],
       [ 0.02800754],
       [ 0.00707706],
       [ 0.03122703],
       [ 0.02749745],
       [ 0.03330447],
       [ 0.06468357],
       [ 0.01555483],
       [-0.02076233],
       [ 0.03046733],
       [ 0.03795574],
       [ 0.02407753],
       [-0.00595498],
       [ 0.01274641],
       [ 0.00399664],
       [ 0.02042477]], dtype=float32)

In [63]:
model.evaluate(tmp_input, tmp_target)

64/64 [==============================] - 0s 2ms/step - loss: 0.1965


0.19645555317401886

In [64]:
reconstructed_model.evaluate(tmp_input, tmp_target)

64/64 [==============================] - 0s 3ms/step - loss: 0.0841


0.08405298739671707

In [65]:
reconstructed_model = keras.models.load_model(model_path)

In [66]:
reconstructed_model.evaluate(tmp_input, tmp_target)

64/64 [==============================] - 0s 3ms/step - loss: 0.1965


0.19645555317401886

In [67]:
np.testing.assert_allclose(model.get_weights()[0], 
                           reconstructed_model.get_weights()[0], 
                           rtol=0.0000001)

In [68]:
reconstructed_model.fit(tmp_input, tmp_target, epochs=5)

Epoch 1/5
64/64 [==============================] - 1s 2ms/step - loss: 0.1866
Epoch 2/5
64/64 [==============================] - 0s 3ms/step - loss: 0.1670
Epoch 3/5
64/64 [==============================] - 0s 3ms/step - loss: 0.1502
Epoch 4/5
64/64 [==============================] - 0s 3ms/step - loss: 0.1363
Epoch 5/5
64/64 [==============================] - 0s 3ms/step - loss: 0.1253


In [69]:
path_2 = "my_model_2"
reconstructed_model.save(path_2)

INFO:tensorflow:Assets written to: my_model_2\assets


INFO:tensorflow:Assets written to: my_model_2\assets


Лучше избегать названия "model", "model_new", model_final

Лучше - осмысленные "yolo_v5_416", "resnet18_epoch100", unet256, unet512

yolo - то то тототото

model_pw_epoch230

In [70]:
model.get_weights()[0].shape

(32, 1)

In [71]:
reconstructed_model.get_weights()[0].shape

(32, 1)

In [72]:
np.testing.assert_allclose(model.get_weights()[0], 
                           reconstructed_model.get_weights()[0], 
                           rtol=0.0000001)

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 32 / 32 (100%)
Max absolute difference: 0.17047672
Max relative difference: 9.558846
 x: array([[ 0.085145],
       [-0.101096],
       [ 0.018775],...
 y: array([[ 0.075164],
       [-0.036714],
       [ 0.038167],...

# Сохранение в формате keras h5

## Базовая модель

In [73]:
def get_model():
    inputs = keras.Input(shape=(32,))
    outputs = keras.layers.Dense(1)(inputs)
    model = keras.Model(inputs, outputs)
    
    model.compile(optimizer="adam", loss="mean_squared_error")
    
    return model

In [74]:
model = get_model()

In [75]:
model.summary()

Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_5 (Dense)             (None, 1)                 33        
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [76]:
test_input = np.random.random((2048, 32))
test_target = np.random.random((2048, 1))

model.fit(test_input, test_target, epochs=4)

Epoch 1/4
64/64 [==============================] - 1s 2ms/step - loss: 0.4869
Epoch 2/4
64/64 [==============================] - 0s 2ms/step - loss: 0.2885
Epoch 3/4
64/64 [==============================] - 0s 2ms/step - loss: 0.2748
Epoch 4/4
64/64 [==============================] - 0s 3ms/step - loss: 0.2595


Сохранение

In [77]:
keras_model_path_1 = "my_keras_model.h5"

In [78]:
model.save(keras_model_path_1, save_format="h5")

Загрузка модели

In [79]:
reconstructed_model = keras.models.load_model(keras_model_path_1)

In [80]:
reconstructed_model.summary()

Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_5 (Dense)             (None, 1)                 33        
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


Сравнение моделей

In [81]:
np.testing.assert_allclose(model.predict(test_input), 
                           reconstructed_model.predict(test_input))

64/64 [==============================] - 0s 2ms/step


Продолжение обучения

In [82]:
reconstructed_model.fit(test_input, test_target, epochs=3)

Epoch 1/3
64/64 [==============================] - 0s 2ms/step - loss: 0.2438
Epoch 2/3
64/64 [==============================] - 0s 3ms/step - loss: 0.2287
Epoch 3/3
64/64 [==============================] - 0s 3ms/step - loss: 0.2127


In [83]:
np.testing.assert_allclose(model.predict(test_input), 
                           reconstructed_model.predict(test_input))

64/64 [==============================] - 0s 2ms/step


AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 2048 / 2048 (100%)
Max absolute difference: 0.26125163
Max relative difference: 59.81042
 x: array([[ 0.895511],
       [ 0.196325],
       [ 1.197542],...
 y: array([[ 0.855859],
       [ 0.260312],
       [ 1.141557],...

In [84]:
reconstructed_model.save("my_keras_model_retrained_epoch_3.h5", save_format="h5")

---

In [85]:
model.evaluate(tmp_input, tmp_target)

64/64 [==============================] - 0s 3ms/step - loss: 0.2487


0.2486688196659088